model:
  channels: 1
  lambda_l1: 100
  learning_rate: 0.0002
  beta_1: 0.5

training:
  epochs: 50
  batch_size: 1
  log_interval: 1000
  checkpoint_interval: 5000
  checkpoint_dir: "./training_checkpoints"

data:
  data_root: "C:\\Users\\qiyuanxu\\Documents\\DataWarehouse\\MMF\\procIMGs\\processed\\"
  train_size: 0.9
  val_size: 0.1
  image_size: [256, 256]
  
logging:
  log_dir: "./logs"
  tensorboard: true