# top‐level paths
paths:
  base: "C:/Users/qiyuanxu/Documents/"    # machine-specific root

model:
  channels: 1
  lambda_l1: 100
  learning_rate: 0.0002
  beta_1: 0.5
  save_path: "DataHub/results/dev/"

training:
  epochs: 50
  batch_size: 1
  log_interval: 1000
  checkpoint_interval: 5000
  checkpoint_dir: "./training_checkpoints"

transforms:
  - name: "load_image"
  - name: "to_narray"
  - name: "to_grayscale"
  - name: "remap_range"
  - name: "split_width"

data:  
  root: "DataHub/local_images/MMF/"
  train_size: 0.9
  val_size: 0.1
  image_size: [256, 256]
  
logging:
  log_dir: "./logs"
  tensorboard: true