# training_config.yaml
epochs: 100
batch_size: 32
validation_freq: 1

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001

early_stopping:
  enabled: true
  patience: 10
  monitor: val_loss

checkpointing:
  enabled: true
  save_best: true
  filepath: "checkpoints/best_model.h5"

callbacks:
  - name: reduce_lr_on_plateau
    patience: 5
    factor: 0.5
  - name: tensorboard
    log_dir: "logs"

metrics:
  - loss
  - accuracy
  - f1_score