# config.yaml
model:
  name: UNet
  encoder_filters: [64, 128, 256, 512]
  decoder_filters: [512, 256, 128, 64]
  activation: relu

data:
  train_images_dir: /path/to/train/images
  train_labels_dir: /path/to/train/labels
  val_images_dir: /path/to/val/images
  val_labels_dir: /path/to/val/labels
  image_size: [256, 256]
  batch_size: 16

training:
  learning_rate: 0.0001
  epochs: 50
  checkpoint_dir: /path/to/checkpoints
  log_dir: /path/to/logs

metadata:
  experiment_name: unet_training
  description: Training configuration for UNet model on image segmentation task
  