seed: 42

paths:
  base: "C:/Users/Documents/"    # machine-specific abs root

framework:
  name: "tensorflow"

model:
  channels: 1
  lambda_l1: 100
  learning_rate: 0.0002
  beta_1: 0.5
  save_path: "./results/pix2pix_generator.keras"

training:
  epochs: 1
  log_interval: 1000
  checkpoint_interval: 5000
  checkpoint_path: "./training_checkpoints"
  save_history_path: "./results/"

data:  
  root: "./DataHub"
  first_split: 0.8
  second_split: 0.5
  image_size: [256, 256]
  dataset_ops: # Dataset-level operations (TensorFlow specific)
    - name: "tf_cache"
    - name: "tf_shuffle"
      params:
        buffer_size: 1000
    - name: "tf_batch"
      params:
        batch_size: 1
    - name: "tf_prefetch"
  transforms:
    numpy:
      - name: "load_image"
      - name: "to_narray"
      - name: "to_grayscale"
      - name: "remap_range"
      - name: "expand_dims"
      - name: "split_width"
      
    tf_native:
      - name: "tf_read_file"
      - name: "tf_decode_image"
      - name: "tf_to_grayscale"
      - name: "tf_normalize"
      - name: "tf_split_width"
        params:
          swap: True


logging:
  log_path: "./logs"
  tensorboard: true